### ISSUE TITLE
embedding in ESM is not extracted from the last layer

### ISSUE THREAD

**Issue by mathpluscode** [DeepChainBio/bio-transformers#12]
Our current code is:

https://github.com/DeepChainBio/bio-transformers/blob/main/biotransformers/wrappers/esm_wrappers.py#L143

But if you check the ESM extract code:

https://github.com/facebookresearch/esm/blob/master/extract.py#L80

You can see if `i = -1`, then `(i + model.num_layers + 1) % (model.num_layers + 1) = model.num_layers`

**Comment by delfosseaurelien** [comment]
Thanks for the fix!
