### ISSUE TITLE
Potential overlap

### ISSUE THREAD

**Issue by sacdallago** [DeepChainBio/bio-transformers#13]
Hi folks :)

looks like a great resource! Funny enough, to be on-topic: seems like an instance of convergent evolution :) https://github.com/sacdallago/bio_embeddings

I see that you are going in some interesting/different directions than what as done on the bio_embeddings side: we'd be happy to see if there are singergies & we can combine efforts rather than maybe distribute it on many different fronts. I also see from [this blog post](https://deepchain.bio/2021/02/24/ai-language-models-offer-a-novel-approach-to-protein-sequence-exploration/) that you are already way ahead on the making the probability plots look beautiful, w.r.t. [my ugly ones](http://data.bioembeddings.com/public/tests/exp_effect/urn:mavedb:00000041-b-1.html) :D

In any case, let's chat if wanted!

CC @konstin

**Comment by adsodemelk** [comment]
Hi @sacdallago definitely there is an overlap in here.  We were not aware of this! Looks great. We will be more than happy to have a chat. If you like the plots, you can create them for free at deepchain.bio, our platform for protein design.   My email is n.lopezcarranza@instadeep.com. We can follow up on a call with our team.
Best,
Nicolas Lopez Carranza
