### ISSUE TITLE
CUDA RUNTIME ERROR

### ISSUE THREAD

**Issue by idmjky** [DeepChainBio/bio-transformers#20]
Hi, 
Thanks for updating the multi-GPU instructions. I am wondering since there is no CUDA toolkit installed during the default installation, do I need to install this aside from the bio-transformers main packages? Also, when I try to run with multi-GPUs, I get this error 
RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

**Comment by delfosseaurelien** [comment]
Hi, you still have this configuration?

Conda torch 1.8.1
NVIDIA-SMI Driver Version: 460.67 CUDA Version: 11.2
Conda cudatoolkit 11.0.221

**Comment by idmjky** [comment]
Yes, I found this seems to be a problem with A600 GPUs only. Others are fine. Thank you for your help.
