### ISSUE TITLE
How to use MSA  transformer embeddings?

### ISSUE THREAD

**Issue by wushixian** [DeepChainBio/bio-transformers#25]
When I calculate MSA embeddings with MSA Transformer model, I get an matrix but not a vector, how can I use the embeddings in downstream tasks? for example I use ['mean'] option to calculate embeddings, and get an matrix include every vector of every sequence in the mean m3a  file, I should use in the downstream  task with the mean value for all rows? or just use the first row? 
Thanks you.

**Comment by delfosseaurelien** [comment]
Hello, it really depends on your need. It could be interesting to take the mean value of all the sequence as the interest of the msa is to catch the evolutionary information of the all the sequences.

**Comment by wushixian** [comment]
OK，I'll try possible embeddings and evaluate the result, thank you!
