### ISSUE TITLE
add finetuning method

### ISSUE THREAD

**Issue by delfosseaurelien** [DeepChainBio/bio-transformers#3]
add method to finetune on personnal protein dataset based on a backend (protbert/ESM) and save trained model.

**Comment by mathpluscode** [comment]
what do you mean `backend` and `register` here, could you clarify a bit :)

**Comment by delfosseaurelien** [comment]
ESM is implemented. We will use the pytorch lightning pipeline to train protbert is the same way.

**Comment by delfosseaurelien** [comment]
ESM/protbert interface merge with pytorch lightning
