### ISSUE TITLE
Wrong formatting in CONTRIBUTING.md - Git conventions

### ISSUE THREAD

**Issue by martinp7** [DeepChainBio/bio-transformers#30]
In the Git conventions section of the CONTRIBUTING.md file, the last item is wrongly formatted cf
![image](https://user-images.githubusercontent.com/27958621/133093899-1c151954-b854-45d4-b80b-8dd29594242d.png)

It should be:

- section:
   - it is optional
   - It is an extension of the section used to add a longer description about the changes if relevant

Also, why the name is `section` and not `<body>` instead?

**Comment by delfosseaurelien** [comment]
done
