### ISSUE TITLE
Use GitHub actions for test and release

### ISSUE THREAD

**Issue by mathpluscode** [DeepChainBio/bio-transformers#6]
As now the repo is public, we can use GitHub actions (https://github.com/features/actions) for 

- Test (Pre-commit check, unit-test, integration-test)
- Documentation build (RTD)
- Release to pip
- Release to docker hub

**Comment by delfosseaurelien** [comment]
Done : Test (Pre-commit check, unit-test, integration-test) >> the test need to be improved
Documentation build (RTD)
Done : Release to pip
Release to docker hub
